version: '3.8'

services:
  app:
    build: .
    container_name: auction_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=adminpassword
      - DB_NAME=AuctionWebsite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=super_secret_jwt_key_2026
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: auction_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=adminpassword
      - MYSQL_DATABASE=AuctionWebsite
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Tự động import database lúc khởi tạo
      - ./AuctionWebsite.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: auction_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: